#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Re-organize .z* files by following the rules here:
# https://thevaluable.dev/zsh-install-configure-mouseless/
# Move environmental variables configured in .zprofile to here
# -- Louis 2024/0312
#
# Put all environmental variables setup back to .zprofile:
# 1. Some how macOS executes:
#    eval "$(/usr/libexec/path_helper -s)"
#    again during login (before .zshenv)
# 2. It ruins the $PATH we expect, which should put our customized paths before
#    system-default paths
# 3. No choice we have to configure $PATH again in .zprofile to ensure the path
#    sequence is what we want
# -- Louis 2024/0316

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
