# ------------------------ General/System
setopt cdablevars                           # Set default zsh options (setopt)

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/zprezto/init.zsh"
fi

source /usr/share/virtualenvwrapper/virtualenvwrapper.sh    # Configure python virtualenvwrapper
pythonPath=$(python3 -c "import site; print(site.getsitepackages()[0])")  # Export 'site-package' path
export PYTHONPATH="${pythonPath}"

# Configure 'zoxide' to replace 'cd'
eval "$(zoxide init zsh)"
alias cd='z'

fpath+="${XDG_CONFIG_HOME}"/zsh/zfunc       # Also add '.zfunc' in $fpath

# ------------------------ Alias/Keybindings/Function
# Move alias definitions to separted file (.zsh_aliases)
if [ -f ${ZDOTDIR:-$HOME}/.zsh_aliases ]; then
    . ${ZDOTDIR:-$HOME}/.zsh_aliases
fi

source <(fzf --zsh)                         # fzf integration

# ------------------------ Others
# Solve 'fzf-tab' doesn't show dot-file/directory issue
# and ignore specific files or folders
# https://github.com/Aloxaf/fzf-tab/issues/476
#_comp_options+=(globdots)
setopt glob_dots
zstyle ':completion:*' ignored-patterns '.DS_Store' '.git' "Icon$'\r'"

# Hightlight dnagerous 'rm -f' command -- Louis 2026/0120
# 1. Enable PCRE (Perl Compatible Regular Expressions)
# This is required for \b (word boundaries) and complex groups to work
zmodload zsh/pcre
setopt RE_MATCH_PCRE

# 2. Define the Highlighter Rules
typeset -A ZSH_HIGHLIGHT_REGEXP

# 3. Add the Rule
# Logic: "rm" -> space -> optional other flags -> flag containing "f"
# Style: White text on Red background (danger!)
# Add '[^|;&]*' at the end to match anything EXCEPT separators
ZSH_HIGHLIGHT_REGEXP+=('\brm\s+(?:-[a-zA-Z]+\s+)*-[a-zA-Z]*f[^|;&]*' 'fg=white,bold,bg=red')

# ------------------------ Hacks/Hooks
# Prompt indicator of subshell triggered by 'yazi'
YAZI_TERM='
[%(!.%B%F{9}%n@%m%f%b.%F{yellow}%n@%m%f):%F{4}${_prompt_nshiu_pwd}%f]${git_info:+${(e)git_info[status]}${(e)git_info[indicator]}}
${python_info:+${(e)python_info[virtualenv]}}%(!. %B%F{9}# %f%b.)%F{12}[ yazi]%f ${editor_info[keymap]} '
if [ -n "$YAZI_LEVEL" ]; then
  PS1="$YAZI_TERM"
fi

# Add 'onefetch' to zsh hook:
# 1. Define 'onefetch' logic
function check_directory_for_new_repository() {
  current_repository=$(git rev-parse --show-toplevel 2> /dev/null)

  if [ "$current_repository" ] && \
     [ "$current_repository" != "$last_repository" ]; then
    # -d: Disable fields that take up space
    # --no-color-palette: Keep it sleek
    # --nerd-fonts: Use icons instead of text blocks
    onefetch -d license churn url head --no-color-palette --nerd-fonts
  fi
  last_repository=$current_repository
}
# 2. Use zsh 'chpwd' hook to trigger 'check_directory_for_new_repository'
autoload -U add-zsh-hook
add-zsh-hook chpwd check_directory_for_new_repository
# 3. Initial check while a shell is startup
check_directory_for_new_repository

# ------------------------ Must be run in the end
# Run compinit to enable autocmopletion update
autoload -Uz compinit
compinit

